### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by hbm50006** [thirdy/blackmarket#13]
It is possible to allow the search to be able to search for specific item names?
For example I want to search for 'Carcass Jack' and only see that item appear.
This would be a great addition.

Thanks for all your work - loving this so far.

**Comment by thirdy** [comment]
i've made a release v0.2-pre-alpha; and it can understand: qotf
which is queen of the forest. this can be extended in the blackmarket.language

but yeah, making it match whole names of uniques is good as well. will work on that next release. thanks for the feedback.

saw your project too, cool

**Comment by hbm50006** [comment]
Very cool, I have been playing with the blackmarket.language for keywords and its working great.
I sent you an email - hopefully to the right gmail one to discuss some more stuff - if you want I can just talk about it on here too.
Basically it's to integrate the use of my searches.json into your program somehow- Anyways thanks for your hard work!

**Comment by thirdy** [comment]
Thanks. I'm looking into tradewatch atm. Taking it easy for now, family day
so it's tiring, need to get lots of sleep.

But I really wanted to ask you this. Is scala really that slow?

I use scala + slick at work. But I'm a noob at scala. And even just
right-clicking onto anything in IntelliJ takes 5 secs. Only happens when
IntelliJ is freshly started. But it's really annoying given that the scala
compiler is slow too. Anything I am missing here?

On Sun, Sep 20, 2015 at 6:39 AM, hbm50006 <notifications@github.com> wrote:

> Very cool, I have been playing with the blackmarket.language for keywords
> and its working great.
> I sent you an email - hopefully to the right gmail one to discuss some
> more stuff - if you want I can just talk about it on here too.
> Basically it's to integrate the use of my searches.json into your program
> somehow- Anyways thanks for your hard work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thirdy/blackmarket/issues/13#issuecomment-141711962>.
>



-- 
--
http://sites.google.com/site/thirdyderivera/

**Comment by thirdy** [comment]
yep got your email, we'll chat there

**Comment by thirdy** [comment]
I am interested on what tradewatch does. I wish I've used it back when I
was really addicted to PoE but I can't even buy myself a CoD! or an upgrade
to my 300pDPS 1h sword.

So this integration sounds cool

On Sun, Sep 20, 2015 at 6:39 AM, hbm50006 <notifications@github.com> wrote:

> Very cool, I have been playing with the blackmarket.language for keywords
> and its working great.
> I sent you an email - hopefully to the right gmail one to discuss some
> more stuff - if you want I can just talk about it on here too.
> Basically it's to integrate the use of my searches.json into your program
> somehow- Anyways thanks for your hard work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thirdy/blackmarket/issues/13#issuecomment-141711962>.
>



-- 
--
http://sites.google.com/site/thirdyderivera/
