### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by Bidalos** [thirdy/blackmarket#16]
When you sort a column, say it pDPS from low to high, normally 49.76 should be above 314.63, etc etc.
http://i.imgur.com/kP2EFVA.png

**Comment by thirdy** [comment]
Yep, all the item attributes right now are in Strings. We'll fix this in the next release.
Thanks for pointing this out.

**Comment by thirdy** [comment]
blackmarket has been overhauled, so this ticket is obsolete now.
On the new version,  sorting is something that needs to be worked on though
