### ISSUE TITLE
update for 1 month leagues

### ISSUE THREAD

**Issue by Moksu** [thirdy/blackmarket#19]
Possible to get an update for the new 1 month leagues? 
Or how to edit the .jar file

**Comment by thirdy** [comment]
You can update the configuration file that was created by blackmarket into your user directory e.g.
C:\Users\yourName.blackmarket\default.properties

You should see a file there called default.properties which has content like this:

https://github.com/thirdy/blackmarket/blob/master/blackmarket/blackmarket-core/src/main/resources/default.properties

Also, I'm near to release v0.4 of blackmarket, hopefully you'll find it lot better, stay tuned!

**Comment by Moksu** [comment]
Hey, thanks for fast respond. 
Do you happen to know what is it enough if i just write it as "Flashback Event" it should show up on the list? or is poe.trade using some funky name

edit: seems like it is using some diffrent name than just Flashback Event. no idea what tho

**Comment by thirdy** [comment]
The key to view the HTTP Request made when a search request is made with poe.trade.

Below is the HTTP request when I opened poe.trade and click that search button right away.

So the answer is: Flashback Event (IC001)

Sorry to talk tech stuff. But just wanted to share some trivia. Good luck, let me know if it works.

league:Flashback Event (IC001)
type:
base:
name:
dmg_min:
dmg_max:
aps_min:
aps_max:
crit_min:
crit_max:
dps_min:
dps_max:
edps_min:
edps_max:
pdps_min:
pdps_max:
armour_min:
armour_max:
evasion_min:
evasion_max:
shield_min:
shield_max:
block_min:
block_max:
sockets_min:
sockets_max:
link_min:
link_max:
sockets_r:
sockets_g:
sockets_b:
sockets_w:
linked_r:
linked_g:
linked_b:
linked_w:
rlevel_min:
rlevel_max:
rstr_min:
rstr_max:
rdex_min:
rdex_max:
rint_min:
rint_max:
impl:
impl_min:
impl_max:
mods:
modexclude:
modmin:
modmax:
mods:
modexclude:
modmin:
modmax:
q_min:
q_max:
level_min:
level_max:
mapq_min:
mapq_max:
rarity:
seller:
thread:
time:2015-10-05
corrupted:
online:
buyout:
altart:
capquality:x
buyout_min:
buyout_max:
buyout_currency:
crafted:
identified:
