### ISSUE TITLE
Maximum stats limits results by alot

### ISSUE THREAD

**Issue by Etheras** [thirdy/blackmarket#26]
Puting my characters max strength, max dex and max int as max attributes for a search i come up with only 2 results. (http://i.imgur.com/EMD5cFa.png)
Removing those, comes up with ALOT more results. (http://i.imgur.com/Fc56vQ5.png)
Edit: Realised might have put the values on the wrong field but putting them on the correct field, does not change much, also putting max required dexterity misses with the whole search ? (with only the limit of a 5link it also shows the chest i purchased yesterday, witch isn't listed and don't know how to force refresh) http://i.imgur.com/ED8HV1O.png

**Comment by thirdy** [comment]
Hi,

For this screenshot:

http://i.imgur.com/Fc56vQ5.png

I think you should remove the **max intelligence attribute of 31**

Let me know if that works, cheers!

**Comment by Etheras** [comment]
but ... that's the screenshot where it actually works as intended.
I'll take more time to look over it.
